import localFont from "next/font/local";
import PropTypes from "prop-types";
import "./globals.css";


const myFontsPrimary = localFont({
  src: "../assets/fonts/dreaming-outloud-script-regular-pro.otf", // Chemin vers votre fichier de police
  variable: "--myFontsPrimary"
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={myFontsPrimary.className}>{children}</body>
    </html>
  );
}
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
